# Generated by Django 4.0.5 on 2023-09-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='MyItem',
        ),
    ]
